stages:
  - docker
  - test
  - deploy

variables:
  CONTAINER_REGISTRY: registry.gitlab.com
  CONTAINER_IMAGE: $CONTAINER_REGISTRY/taig-github/lokal
  DOCKER_DRIVER: overlay2

docker:
  stage: docker
  image: docker
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CONTAINER_REGISTRY
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA .
    - docker push $CONTAINER_IMAGE

test-jvm:
  stage: test
  image: $CONTAINER_IMAGE:$CI_COMMIT_SHA
  script:
    - sbt -Dmode=strict scalafmtCheckAll coverage +coreJVM/test +dslJVM/test coverageAggregate
    - mv target/scala-2.13/scoverage-report/ coverage/
  artifacts:
    expire_in: 1 month
    paths:
      - coverage/

test-js:
  stage: test
  image: $CONTAINER_IMAGE:$CI_COMMIT_SHA
  script:
    - sbt -Dmode=strict +coreJS/test +dslJS/test

artifacts:
  stage: deploy
  image: $CONTAINER_IMAGE:$CI_COMMIT_SHA
  only:
    - master
    - tags
  script:
    - sbt publishAndRelease

pages:
  stage: deploy
  image: $CONTAINER_IMAGE:$CI_COMMIT_SHA
  only:
    - tags
  script:
    - sbt website/makeMicrosite
    - mv website/target/site/ public/
    - mv coverage/ public/coverage/
  artifacts:
    paths:
      - public/
  dependencies:
    - test-jvm